name: auth
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  beamer: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Libadora
  #     fonts:
  #       - asset: assets/fonts/Libadora-Regular.ttf
  #       - asset: assets/fonts/Libadora-Bold.ttf
  #         weight: 700